apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprofile-app
  template:
    metadata:
      labels:
        app: vprofile-app
    spec:
      containers:
      - name: vprofile-app
        image: kanukhosla10/vprofileappimg:latest
        ports:
        - containerPort: 8080
