Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = true
    
#   ### jenkins vm  ####
#     config.vm.define "jenkins" do |jenkins01|
#       jenkins01.vm.box = "bytesguy/ubuntu-server-20.04-arm64"
#       jenkins01.vm.hostname = "jenkins"
#       jenkins01.vm.network "private_network", ip: "192.168.56.25"
#     #   jenkins01.vm.provider "vmware_fusion" do |vmware|
#     #     #vmware.gui = true
#     #     vmware.memory = "1024"
#     #     vmware.allowlist_verified = true
#     #   end
#     end
### DB vm  ####
    config.vm.define "db01" do |db01|
      db01.vm.box = "jacobw/fedora35-arm64"
      db01.vm.hostname = "db01"
      db01.vm.network "private_network", ip: "192.168.56.25"
      #db01.vm.provision "shell", path: "mysql.sh"  

  end

#   ### nexus vm  #### 
#     config.vm.define "nexus" do |nexus|
#       nexus.vm.box = "svergun/centos9s-arm64"
#       nexus.vm.hostname = "nexus"
#       nexus.vm.network "private_network", ip: "192.168.40.2"
#       nexus.vm.provider "vmware_fusion" do |vmware|
#         vmware.gui = true
#         vmware.allowlist_verified = true
#       end
#     end
    
#   ### sonarqube vm  ####
#     config.vm.define "sonarqube" do |sonarqube|
#       sonarqube.vm.box = "bytesguy/ubuntu-server-20.04-arm64"
#       sonarqube.vm.hostname = "sonarqube"
#       sonarqube.vm.network "private_network", ip: "192.168.40.3"
#       sonarqube.vm.provider "vmware_desktop" do |vmware|
#         vmware.gui = true
#         vmware.allowlist_verified = true
#       end
#     end
    
#   ### tomcat vm ###
#     config.vm.define "app01" do |app01|
#       app01.vm.box = "jacobw/fedora35-arm64"
#       app01.vm.hostname = "app01"
#       app01.vm.network "private_network", ip: "192.168.56.12"
#       app01.vm.provider "vmware_desktop" do |vb|
#        vb.memory = "1024"
#        vb.gui = true
#        vb.allowlist_verified = true
#       end
#     end
     
    
#   ### Nginx VM ###
#     config.vm.define "web01" do |web01|
#       web01.vm.box = "spox/ubuntu-arm"
#       web01.vm.hostname = "web01"
#       web01.vm.network "private_network", ip: "192.168.56.11"
#       web01.vm.provider "vmware_desktop" do |vmware|
#         vmware.gui = true
#         vmware.allowlist_verified = true
#       end
  
#     end 

  end