def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger'
]

pipeline {
    agent any
    stages {
        stage('Deploy the app to Minikube') {
            steps {
                script {
                    sh 'kubectl apply -f app-deployment/vprofile-deployment.yml'
                    sh 'kubectl apply -f app-deployment/vprofile-service.yml'
                }
            }
        }
    }

    
    post {
            always {
                echo 'Slack Notifications.'
                slackSend channel: '#ci-build-local',
                    color: COLOR_MAP[currentBuild.currentResult],
                    message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} Build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
            }
        }
}
